### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by liluoqinchuan** [HKUST-Aerial-Robotics/Stereo-RCNN#26]
Hi  PeiLiang:
    When I trained the model to 3682 iterations of the first epoch, I encountered the following problems:
    
 IndexError: Traceback (most recent call last):
  File "/home/zhaodan/Downloads/sofaware/pycharm-community-2018.3.1/venvpy2/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 42, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zhaodan/Downloads/code/Stereo-RCNN-master1/lib/roi_data_layer/roibatchLoader.py", line 65, in __getitem__
    blobs = get_minibatch(minibatch_db, self._num_classes)
  File "/home/zhaodan/Downloads/code/Stereo-RCNN-master1/lib/roi_data_layer/minibatch.py", line 34, in get_minibatch
    im_blob_left, im_blob_right, im_scales = _get_image_blob(roidb, random_scale_inds)
  File "/home/zhaodan/Downloads/code/Stereo-RCNN-master1/lib/roi_data_layer/minibatch.py", line 114, in _get_image_blob
    img_right = img_right[:,:,::-1]
IndexError: too many indices for array

  Do you have such a problem?

  My GPU is nvidia GTX 1081Ti , its memory size  is 11G ,  does it enough?

  Looking forward to your reply！ Thanks!

**Comment by PeiliangLi** [comment]
Are you using gray scale images?

**Comment by liluoqinchuan** [comment]
I downloaded the data according to the link given：

![image](https://user-images.githubusercontent.com/51945097/59742605-b2945900-92a0-11e9-9e7f-492fb086eaea.png)

![image](https://user-images.githubusercontent.com/51945097/59742589-a9a38780-92a0-11e9-8146-eac9461da2ec.png)

**Comment by PeiliangLi** [comment]
Can you print the shape of the img_right?
