### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets.factory'

### ISSUE THREAD

**Issue by JensenGao** [HKUST-Aerial-Robotics/Stereo-RCNN#29]
Hello, 
I am getting the following error when I run '**python demo.py**'：
Traceback (most recent call last):
  File "demo.py", line 25, in <module>
    from roi_data_layer.roidb import combined_roidb
  File "ptah_of_project/Stereo-RCNN/lib/roi_data_layer/roidb.py", line 9, in <module>
    from datasets.factory import get_imdb
**ModuleNotFoundError: No module named 'datasets.factory'**

And my environment of python is same to the source code.

Before I run "python demo.py", I have build successful by "python setup.py build develop", 
I hope you can give me some  suggestions to fix the problem. Thanks
!

**Comment by JensenGao** [comment]
add /lib dictronary to environment use:
export PYTHONPATH=～/Stereo-RCNN/lib
and it works
