### ISSUE TITLE
undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by DasReich** [HKUST-Aerial-Robotics/Stereo-RCNN#58]
Hi,when i tried to run demo.py in mono branch,an error occured:
Traceback (most recent call last):
  File "demo.py", line 30, in <module>
    from model.nms.nms_wrapper import nms
  File "/home/lcj/code/stereo/mono/lib/model/nms/nms_wrapper.py", line 10, in <module>
    from model.nms.nms_gpu import nms_gpu
  File "/home/lcj/code/stereo/mono/lib/model/nms/nms_gpu.py", line 4, in <module>
    from ._ext import nms
  File "/home/lcj/code/stereo/mono/lib/model/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: /home/lcj/code/stereo/mono/lib/model/nms/_ext/nms/_nms.so: undefined symbol: __cudaPopCallConfiguration
The environment is the same as you provided and "sh make.sh" was successful.Hope you could give me the answer,thanks.

**Comment by ycj1124** [comment]
same questions. did you find the solution?
