### ISSUE TITLE
ImportError: /N/slate/piyush/dl/Stereo-RCNN/lib/model/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

### ISSUE THREAD

**Issue by pyyush** [HKUST-Aerial-Robotics/Stereo-RCNN#61]
(dl) [piyush@dl1 Stereo-RCNN]$ ./train.sh 
Traceback (most recent call last):
  File "trainval_net.py", line 33, in <module>
    from model.stereo_rcnn.resnet import resnet
  File "/N/slate/piyush/dl/Stereo-RCNN/lib/model/stereo_rcnn/resnet.py", line 6, in <module>
    from model.stereo_rcnn.stereo_rcnn import _StereoRCNN
  File "/N/slate/piyush/dl/Stereo-RCNN/lib/model/stereo_rcnn/stereo_rcnn.py", line 17, in <module>
    from model.rpn.stereo_rpn import _Stereo_RPN
  File "/N/slate/piyush/dl/Stereo-RCNN/lib/model/rpn/stereo_rpn.py", line 13, in <module>
    from model.rpn.proposal_layer import _ProposalLayer
  File "/N/slate/piyush/dl/Stereo-RCNN/lib/model/rpn/proposal_layer.py", line 20, in <module>
    from model.roi_layers import nms
  File "/N/slate/piyush/dl/Stereo-RCNN/lib/model/roi_layers/__init__.py", line 3, in <module>
    from .nms import nms
  File "/N/slate/piyush/dl/Stereo-RCNN/lib/model/roi_layers/nms.py", line 3, in <module>
    from model import _C
ImportError: /N/slate/piyush/dl/Stereo-RCNN/lib/model/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

**Comment by bricksaver** [comment]
How did you end up solving this?
