### ISSUE TITLE
Branch Mono on Google Colab

### ISSUE THREAD

**Issue by ianw4tm** [HKUST-Aerial-Robotics/Stereo-RCNN#62]
I ran the Branch 1.0 using Google Colab successfully. 
Unfortunately, I have problems with the Branches Mono & Master when using Colab.

The problem happens when I try to run this line: "sh make.sh" which appears on the step 0.2. Build
For the branch 1.0 instead of using that last line, I used this other one: "python setup.py build develop" and everything worked fine.
Does anyone know if there's a problem using the "sh" command on Google Colab? Any advice?

This is the error:

/content/stereo_rcnn/lib
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
Compiling nms kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import torch
  File "/usr/local/lib/python3.6/site-packages/torch/__init__.py", line 56, in <module>
    from torch._C import *
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory
Compiling roi align kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 2, in <module>
    import torch
  File "/usr/local/lib/python3.6/site-packages/torch/__init__.py", line 56, in <module>
    from torch._C import *
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory
/content/stereo_rcnn

Thanks in advance.

**Comment by ahmedyahia1060** [comment]
can you tell me how to use google colab with this code

**Comment by wyq-cqupt** [comment]
> 你能告诉我如何在这段代码中使用 google colab
![截屏2021-11-03 19 33 36](https://user-images.githubusercontent.com/93653881/140053077-0619f76a-11cf-4bb2-87c0-98da0a45fca8.png)
