### ISSUE TITLE
ImportError: cannot import name '_C'

### ISSUE THREAD

**Issue by Yimuer** [HKUST-Aerial-Robotics/Stereo-RCNN#80]
Traceback (most recent call last):
  File "E:/All Code Files/python files/Stereo-RCNN/demo.py", line 29, in <module>
    from model.roi_layers import nms
  File "E:\All Code Files\python files\Stereo-RCNN\lib\model\roi_layers\__init__.py", line 3, in <module>
    from .nms import nms
  File "E:\All Code Files\python files\Stereo-RCNN\lib\model\roi_layers\nms.py", line 3, in <module>
    from model import _C
ImportError: cannot import name '_C'

**Comment by yao666-creater** [comment]
I also encountered this problem, have you solved it now?

**Comment by Wyx9352** [comment]
Have you built it yet? The build command is in the "0.2.build" step of the readme file. I solved the problem after I built it

**Comment by yao666-creater** [comment]
> 你建好了吗？构建命令位于自述文件的“ 0.2.build”步骤中。建好后我解决了这个问题

Thank you for your reply, I have solved this problem

**Comment by yao666-creater** [comment]
> Have you built it yet? The build command is in the "0.2.build" step of the readme file. I solved the problem after I built it

Thank you for your reply, I have solved this problem

**Comment by abhishekt711** [comment]
Please post the solution. How you had solved this problem?

**Comment by Lq112211** [comment]
> > Have you built it yet? The build command is in the "0.2.build" step of the readme file. I solved the problem after I built it
> 
> Thank you for your reply, I have solved this problem

How did you solve it? Can you tell me more details about it.
